### PR TITLE
Vis 2nd try

### PR DESCRIPTION
**Pull request by AnnaSus1ova**
Try to megre two branches
1) Add two additional buttons
2) Add special data containers

### CODE REVIEW

**Comment by Alesialoco** [comment]
Work well

**Comment by Nattie68** [comment]
The authors are genius, the code is a masterpiece

**Comment by AnnaSus1ova** [comment]
The code is perfect, I'll hang it on the wall in a frame 💪💪💪

**Comment by Anactaciya** [comment]
Wow 💅

**Pull request merged**
